---
# handlers file for install-packages
- name: Restart NTP
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Restart Chrony
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"