---
# tasks file for install-jenkins


#=========START BLOCK FOR DEBIAN=========
- block:


  #apt repo
  - name: Add Apt signing key from official jenkins repo Debian
    apt_key:
      url: "{{ jenkins_repo_keyurl }}"
      state: present


  - name: Add jenkins repository Debian
    apt_repository:
      repo: "{{ jenkins_repo_repourl }}"
      filename: "{{ jenkins_repo_repofilename }}"
      state: present


  #update and install packages
  - name: Include the 'dist-upgrade' role
    include_role:
      name: dist-upgrade


  - name: Intall Java nginx packages.
    apt: 
      name:
        - openjdk-11-jre
        - nginx
      state: latest
      install_recommends: yes


  - name: Intall Jenkins package.
    apt: 
      name:
        - jenkins
      state: latest
      install_recommends: yes


  - name: Copy over the jenkins configuration
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "{{ jenkins_conf_debian_dest }}"
      owner: root
      group: root
      mode: '0644'
    with_items:
      - "jenkins.debian.j2"
    notify: Restart jenkins


  - iptables:
      chain: INPUT
      source: localhost
      destination_port: 8080
      protocol: tcp
      jump: ACCEPT


  - iptables:
      chain: INPUT
      destination_port: 443
      protocol: tcp
      jump: ACCEPT


  - iptables:
      chain: INPUT
      destination_port: 8080
      protocol: tcp
      jump: DROP


  when: ansible_os_family == "Debian"
#=========END BLOCK FOR DEBIAN=========




#=========START BLOCK FOR REDHAT=========
- block:


  #rpm repo
  - name: Add jenkins repository RedHat
    get_url:
      url: "{{ jenkins_rpm_repo_url }}"
      dest: /etc/yum.repos.d/jenkins.repo


  - name: Add Jenkins GPG key from official jenkins repo RedHat
    rpm_key:
      state: present
      key: "{{ jenkins_rpm_repo_key_url }}"


  #update and install packages
  - name: Include the 'dist-upgrade' role
    include_role:
      name: dist-upgrade


  - name: Intall packages.
    yum:
      name:
        - java-11-openjdk.x86_64
        - nginx
        - jenkins
      state: latest

  - name: Copy over the jenkins configuration
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "{{ jenkins_conf_redhat_dest }}"
      owner: root
      group: root
      mode: '0644'
    with_items:
      - "jenkins.redhat.j2"
    notify: Restart jenkins


#?!?!?!
  - name: Disable SELinux
    selinux:
      state: disabled


  - firewalld:
      port: 443/tcp
      permanent: true
      state: enabled
    notify: Restart firewalld


  when: ansible_os_family == "RedHat"
#=========END BLOCK FOR REDHAT=========



#=========START COMMON BLOCK=========

- block:


  #copy conf files
  - name: Copy over the nginx configuration
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "{{ nginx_conf_dest }}"
      owner: root
      group: root
      mode: '0644'
    with_items:
      - "nginx.conf"
      - "cert.key"
      - "cert.crt"
    notify: Restart nginx