---
# tasks file for pve-no-subscription-repository

- name: Intall python-apt.
  shell: test -e /usr/share/python-apt || ( apt update; apt install -y python-apt )
  when: 
    - ansible_os_family == "Debian" and 
      inventory_hostname in groups['pve']

- name: remove proxmox enterprise repo
  apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise"
    state: absent
    filename: 'pve-enterprise'
  when: 
    - ansible_os_family == "Debian" and 
      inventory_hostname in groups['pve']

- name: Add proxmox key
  apt_key:
    url: "{{ pve_repo_keyurl }}"
    keyring: "{{ pve_repo_keyring }}"
    state: present
  when: 
    - ansible_os_family == "Debian" and 
      inventory_hostname in groups['pve']

- name: Add proxmox repository
  apt_repository:
    repo: "{{ pve_repo_repourl }}"
    filename: "{{ pve_repo_repofilename }}"
    state: present
  when: 
    - ansible_os_family == "Debian" and 
      inventory_hostname in groups['pve']
