---
  # tasks file for install-python-pip
  - name: Ensure Pip is installed.
    apt:
      name: 
        - python3-pip
        - python-pkg-resources
      state: latest
      update_cache: yes
      install_recommends: yes
    when: ansible_os_family == "Debian"
  
  - name: Ensure Pip is installed.
    yum:
      name: 
        - python3-pip
      state: latest
    when: ansible_os_family == "RedHat"
  
  - name: Ensure pip_install_packages are installed.
    pip:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default(omit) }}"
      virtualenv: "{{ item.virtualenv | default(omit) }}"
      state: latest
      executable: "{{ pip_executable }}"
    with_items: "{{ pip_install_packages }}"